site_name: trubrics-sdk
site_description: Combine data science knowledge with business user feedback to validate machine learning
repo_url: https://github.com/trubrics/trubrics-sdk.git
repo_name: trubrics/trubrics-sdk
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members:
                -
  - search
  - mkdocs-jupyter
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  logo: assets/logo-white.png
  favicon: assets/logo-flavicon.png
  palette:
    scheme: slate
  font:
    text: Montserrat
  icon:
    admonition:
      note: octicons/tag-16
      example: octicons/beaker-16
    repo: material/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Getting Started: index.md
  - Tutorials:
    - Titanic classifier example: classifier_tutorial.md
    - Titanic classifier notebook: notebooks/titanic-demo.html
  - The DataContext: data_context.md
  - Features:
    - Models: models.md
    - Validations:
      - The ModelValidator object: validator_object.md
      - Out-of-the-box validations: validations.md
      - Custom validations: custom_validations.md
    - Running trubrics (CLI): run_trubrics.md
    - Collecting user feedback: feedback.md
    - (WIP) Logging trubrics to the UI: log_trubrics.md
copyright: Copyright © 2022 Trubrics Ltd. All rights reserved. Trubrics and the Trubrics logo are trademarks of Trubrics Ltd.