site_name: trubrics-sdk
site_description: Combine data science knowledge with business user feedback to validate machine learning
repo_url: https://github.com/trubrics/trubrics-sdk.git
repo_name: trubrics/trubrics-sdk
plugins:
  - mkdocstrings
  - search
  - mkdocs-jupyter
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  logo: assets/logo-white.png
  palette:
    scheme: slate
  font:
    text: Montserrat
  icon:
    admonition:
      note: octicons/tag-16
      example: octicons/beaker-16
    repo: material/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Getting Started: index.md
  - Tutorials:
    - Titanic classifier example: classifier_tutorial.md
    - Titanic classifier notebook: notebooks/titanic-demo.ipynb
  - Contexts: context.md
  - Features:
    - Running trubrics: run_trubrics.md
    - (WIP) Logging trubrics to the UI: log_trubrics.md
  - Validations:
    - Out of the box: validations.md
    - Custom: custom_validations.md
