site_name: trubrics-sdk
site_description: Combine data science knowledge with business user feedback to validate machine learning
repo_url: https://github.com/trubrics/trubrics-sdk.git
repo_name: trubrics/trubrics-sdk
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members:
                -
  - search
  - mkdocs-jupyter
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  logo: assets/logo-white.png
  favicon: assets/logo-favicon.png
  palette:
    scheme: slate
  font:
    text: Montserrat
  icon:
    admonition:
      note: octicons/tag-16
      example: octicons/beaker-16
    repo: material/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Getting Started: index.md
  - Trubrics platform:
    - Account setup: trubrics_platform/account_setup.md
    - ✏️ Feedback components: trubrics_platform/feedback_components.md
    - 🪄 Insights: trubrics_platform/insights.md
    - ⚠️ Issues: trubrics_platform/issues.md
  - Integrations:
    - Streamlit: integrations/streamlit.md
    # - Gradio: integrations/gradio.md
    # - Dash: integrations/dash.md
    - Flask: integrations/flask_example.md
    - MLflow (validations): integrations/mlflow.md
  - ML Validations:
    - DataContext: validations/data_context.md
    - Compatible models: validations/models.md
    - Metrics: validations/metrics.md
    - Out-of-the-box validations: validations/validations.md
    - Custom validations: validations/custom_validations.md
    - Save validations as a trubric: validations/save_trubric.md
    - Run validations from CLI: validations/trubrics_cli.md
    - Tutorials: validations/tutorials.md

copyright: Copyright © 2022 Trubrics Ltd. All rights reserved. Trubrics and the Trubrics logo are trademarks of Trubrics Ltd.