site_name: trubrics-sdk
site_description: Combine data science knowledge with business user feedback to validate machine learning
theme:
  name: material
  logo: assets/logo-white.png
  palette:
    scheme: slate
  font:
    text: Montserrat
  icon:
    admonition:
      note: octicons/tag-16
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
nav:
  - Getting Started: index.md
  - Tutorials:
    - Titanic Classifier Example: train_titanic.md
  - Contexts: context.md
  - Features:
    - Running Trubrics: run_trubrics.md
    - Logging Trubrics to the UI: log_trubrics.md
  - Validations:
    - Out of the box: validations.md
    - Build Custom Validations: custom_validations.md
