name: test release

on:
  push:
    tags:
      - v1.0.2

jobs:
  build-and-publish:
    name: test release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Extract release notes
      id: extract-release-notes
      uses: ffurrer2/extract-release-notes@v1
    - name: Create github release
      if: startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.extract-release-notes.outputs.release_notes }}
        files: dist/*.whl
